### PR TITLE
Backend for files API

### PR DESCRIPTION
**Pull request by Letaldiran**

### CODE REVIEW

**Comment by Letaldiran** [comment]
[Create Files table, migrations and corresponding form for accepting files](https://trello.com/c/CqFMVUjg/12-create-files-table-migrations-and-corresponding-form-for-accepting-files)

**Comment by Letaldiran** [comment]
[Realise CRUD operations for files/folders and uploading of files](https://trello.com/c/ziPcbBtE/13-realise-crud-operations-for-files-folders-and-uploading-of-files)

**Comment by Letaldiran** [comment]
[Add SafeDelete option for files](https://trello.com/c/4kaiKYIK/14-add-safedelete-option-for-files)

**Comment by Letaldiran** [comment]
[Create ShareLink table and migrations](https://trello.com/c/REdTQR4R/15-create-sharelink-table-and-migrations)

**Comment by Letaldiran** [comment]
[Add API endpoint with creation of share links for files with certain time expiry](https://trello.com/c/lQCXZEdX/23-add-api-endpoint-with-creation-of-share-links-for-files-with-certain-time-expiry)

**Review by pyaremenko — APPROVED** [review]
great ass, good balls

**Pull request merged**
